title: Jason N. Gaylord
subtitle: <i class="fas fa-people-arrows"></i> Social Distancing since 3/14
author: Jason N. Gaylord
description: >
  Here is my website. This description will appear in the meta
  data on the site and in the feed.xml site description.
baseurl: /JasonGaylord.com

# git edit capabilities
remote_theme: jasongaylord/SpaacedOut
git:
  owner: jasongaylord
  repository: JasonGaylord.com
  branch: master

# pagination and permalink
show_excerpts: true
paginate: 5
page_group_size: 5
paginate_path: "/blog/page/:num"
permalink: /blog/:year/:month/:day/:title

# content expansion
content:
  head-s: true
  header-s: true
#  header-suffix: header-suffix.html
#  head-suffix: head-suffix.html  

# contact
contact: 
  avatar-image: /JasonGaylord.com/assets/images/jason.png
#  email: email@gmail.com # Uncomment if you want feedback via email (it will expose your email)
#  url: https://domain.com/contact.html # Uncomment if you want to provide a contact form

# social links (uncomment the links you'd like to include and)
social:
  facebook: jason.gaylord
  github: jgaylord
  instagram: jason.gaylord
  linkedin: jasongaylord
#  pinterest: jekyll
#  stackoverflow: "11111"
  twitter: jgaylord
#  youtube: jekyll

google:
  analytics: UA-2053573-1
  adsense: ca-pub-2663334448189019

rss: rss
# The site generates a feed at /feed.xml. Uncomment below to override
# feed:
#   path: /myfeed.xml

# comments
comments:
  enabled: true
  show_count: true
  disqus_shortname: jasongaylord

# front matter
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      comments: true
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: page
      comments: false
  -
    scope:
      path: "assets/pages"
      type: "pages"
    values:
      layout: page
      comments: false

#Kramdown Configuration      
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

#Plugins and configuration
future: false
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap